### ISSUE TITLE
Execute PHP code from Twig

### ISSUE THREAD

**Issue by WalterPrech** [antistatique/drupal-bamboo-twig#44]
We have used the 'php'-module in drupal 7 and want now to upgrade to drupal 9.

We have fields with the text format 'php' for example like this:
```
<?php 
    $nid_1 = 989;
    global $language;
    $lang_name = $language->language;
    $node_1 = node_load($nid_1);
    $view_1 = node_view($node_1, 'ads_one_column_abfallend', $lang_name);
    print render($view_1);
?>
```
We take a node id and render it with a special view.

Is it possible to use bamboo_twig to do something similiar?

Do you have an example, how to use php in a template?

**Comment by WengerK** [comment]
nop it's not possible and highly un-recommended as you now (drupal 8+) have the power of Twig for templating :)

ps: sorry for the massive delay on answering ... :/
